apiVersion: v1
kind: Service
metadata:
  name: runbook-alpine
  namespace: default 
  labels:
    app: runbook-alpine-app
spec:
  selector:
    app: runbook-alpine-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
