apiVersion: apps/v1
kind: Deployment
metadata:
  name: runbook-amazonlinux
  namespace: default
  labels:
    app: runbook-amazonlinux-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: runbook-amazonlinux-app
  template:
    metadata:
      labels:
        app: runbook-amazonlinux-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  #                - amd64
                - arm64
      containers:
      - name: runbook-amazonlinux
        image: aws_account_id.dkr.ecr.aws_region.amazonaws.com/runbook-amazonlinux:1.0
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
