apiVersion: v1
kind: Service
metadata:
  name: runbook-amazonlinux
  namespace: default 
  labels:
    app: runbook-amazonlinux-app
spec:
  selector:
    app: runbook-amazonlinux-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
